# Generated by Django 6.0.7 on 2026-07-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('topics', models.TextField()),
                ('exam_type', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('no_of_questions', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('generated_content', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_papers/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated_papers/docx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
